// Copy one E2E run (results.json, screenshots, MP4 recordings) into the app so /review can show it.
// Usage: node import-run.mjs <runDir> <projectDir> <runId> <ffprobe.exe>
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const [RUN, PROJ, ID, FFPROBE] = process.argv.slice(2);
const data = JSON.parse(readFileSync(join(RUN, 'results.json'), 'utf8'));
const pub = join(PROJ, 'public', 'review', ID);
mkdirSync(join(pub, 'shots'), { recursive: true });
mkdirSync(join(pub, 'video'), { recursive: true });

const seconds = (f) => {
  const r = spawnSync(FFPROBE, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]);
  return Math.round(parseFloat(String(r.stdout)) * 10) / 10 || 0;
};

let offset = 0;
const stages = data.results.map((s) => {
  const mp4 = s.video ? s.video.replace(/\.webm$/, '.mp4') : null;
  const src = mp4 && join(RUN, 'video', mp4);
  let video = null, duration = 0;
  if (src && existsSync(src)) { copyFileSync(src, join(pub, 'video', mp4)); video = `/review/${ID}/video/${mp4}`; duration = seconds(src); }
  const stage = {
    num: s.num, name: s.name, viewport: s.viewport, video, duration, startsAt: offset,
    consoleErrors: s.consoleErrors ?? [], fatal: s.fatal ?? null,
    steps: s.steps.map((t) => {
      if (t.shot && existsSync(join(RUN, 'shots', t.shot))) copyFileSync(join(RUN, 'shots', t.shot), join(pub, 'shots', t.shot));
      return { n: t.n, title: t.title, ok: t.ok, error: t.error ?? null, ms: t.ms, url: t.url, shot: t.shot ? `/review/${ID}/shots/${t.shot}` : null };
    }),
  };
  offset += duration;
  return stage;
});

const full = join(RUN, 'video', 'samaritanlink-full-test.mp4');
let fullVideo = null;
if (existsSync(full)) { copyFileSync(full, join(pub, 'video', 'full-test.mp4')); fullVideo = `/review/${ID}/video/full-test.mp4`; }

const run = { id: ID, base: data.base, startedAt: data.startedAt, finishedAt: data.finishedAt, fullVideo, stages };
const dataDir = join(PROJ, 'src', 'data', 'review');
mkdirSync(dataDir, { recursive: true });
writeFileSync(join(dataDir, `${ID}.json`), JSON.stringify(run, null, 2) + '\n');

// Regenerate the index of runs, newest first.
const ids = readdirSync(dataDir).filter((f) => /^\d{4}-\d{2}-\d{2}.*\.json$/.test(f)).map((f) => f.replace(/\.json$/, '')).sort().reverse();
const ident = (id) => 'run_' + id.replace(/\W/g, '_');
writeFileSync(join(dataDir, 'index.ts'),
  `// Generated by the E2E import script. One JSON file per recorded test run, newest first.\n` +
  `import type { ReviewRun } from "./types";\n` +
  ids.map((id) => `import ${ident(id)} from "./${id}.json";`).join('\n') +
  `\n\nexport const RUNS: ReviewRun[] = [${ids.map(ident).join(', ')}] as ReviewRun[];\n`);

const steps = stages.flatMap((s) => s.steps);
console.log(`imported ${ID}: ${stages.length} stages, ${steps.filter((t) => t.ok).length}/${steps.length} passed, full video ${fullVideo ? 'yes' : 'no'}, ${Math.round(offset)} s recorded`);
