// Generated by the E2E import script. One JSON file per recorded test run, newest first.
import type { ReviewRun } from "./types";
import run_2026_10_08 from "./2026-10-08.json";
import run_2026_10_07 from "./2026-10-07.json";

export const RUNS: ReviewRun[] = [run_2026_10_08, run_2026_10_07] as ReviewRun[];
